/**
 * Sui-Gen Formatters Module
 * Converts canonical dataset array into various output formats.
 * Each function takes an array of objects and returns a string.
 */

/**
 * JSON — Pretty-printed with 2-space indent.
 */
export function toJSON(data) {
    return JSON.stringify(data, null, 2);
}

/**
 * CSV — RFC-4180 compliant.
 * Quotes fields containing commas, quotes, or newlines.
 * Escapes double-quotes by doubling them.
 */
export function toCSV(data) {
    if (!data.length) return '';
    const keys = Object.keys(data[0]);
    const lines = [];

    // Header
    lines.push(keys.join(','));

    // Rows
    for (const row of data) {
        const cells = keys.map(k => csvEscape(row[k]));
        lines.push(cells.join(','));
    }
    return lines.join('\n');
}

function csvEscape(val) {
    if (val === null || val === undefined) return '';
    const s = String(val);
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
        return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
}

/**
 * YAML — Simple block-style, no anchors or aliases.
 */
export function toYAML(data) {
    if (!data.length) return '';
    const lines = [];
    for (const row of data) {
        let first = true;
        for (const [key, val] of Object.entries(row)) {
            const prefix = first ? '- ' : '  ';
            first = false;
            lines.push(prefix + key + ': ' + yamlValue(val));
        }
    }
    return lines.join('\n');
}

function yamlValue(val) {
    if (val === null || val === undefined) return 'null';
    if (typeof val === 'number') return String(val);
    const s = String(val);
    // Quote strings that could be misinterpreted
    if (/^[\d]/.test(s) || /[:#{}[\],&*?|>!'"%@`]/.test(s) || s === '' || s === 'null' || s === 'true' || s === 'false') {
        return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
    }
    return s;
}

/**
 * SQL — INSERT INTO statements for table `sui_gen_cny`.
 * Dynamic columns based on data keys.
 */
export function toSQL(data) {
    if (!data.length) return '';
    const keys = Object.keys(data[0]);
    const lines = [];

    // Schema comment
    lines.push('-- Generated by Sui-Gen (https://github.com/twinysam/sui-gen)');
    lines.push('-- Table: sui_gen_cny');
    lines.push('');

    // CREATE TABLE
    const colDefs = keys.map(k => {
        if (k === 'year') return '  year INTEGER PRIMARY KEY';
        if (k === 'yearLength' || k === 'leapMonth') return `  ${k} INTEGER`;
        return `  ${k} TEXT`;
    });
    lines.push('CREATE TABLE IF NOT EXISTS sui_gen_cny (');
    lines.push(colDefs.join(',\n'));
    lines.push(');');
    lines.push('');

    // INSERT statements
    for (const row of data) {
        const vals = keys.map(k => sqlValue(row[k]));
        lines.push(`INSERT INTO sui_gen_cny (${keys.join(', ')}) VALUES (${vals.join(', ')});`);
    }
    return lines.join('\n');
}

function sqlValue(val) {
    if (val === null || val === undefined) return 'NULL';
    if (typeof val === 'number') return String(val);
    const s = String(val).replace(/'/g, "''");
    return "'" + s + "'";
}

/**
 * Markdown — GitHub-Flavored Markdown table.
 */
export function toMarkdown(data) {
    if (!data.length) return '';
    const keys = Object.keys(data[0]);
    const lines = [];

    // Header
    lines.push('| ' + keys.join(' | ') + ' |');

    // Separator (right-align numbers)
    const seps = keys.map(k => {
        if (k === 'year' || k === 'yearLength' || k === 'leapMonth') return '---:';
        return '---';
    });
    lines.push('| ' + seps.join(' | ') + ' |');

    // Rows
    for (const row of data) {
        const cells = keys.map(k => {
            const v = row[k];
            return v === null || v === undefined ? '' : String(v);
        });
        lines.push('| ' + cells.join(' | ') + ' |');
    }
    return lines.join('\n');
}
